stages:
  - docker_image
  - build
  - test

variables:
  DOCKER_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG

build_image:
  stage: docker_image
  only:
    changes:
      - .gitlab-ci.yml
      - build-config/gitlab-docker/Dockerfile
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE build-config/gitlab-docker
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE

build-ci-test:
  stage: build
  only:
    - ci-test
  image: $DOCKER_IMAGE
  script:
    - cd libevent-2.1.11-stable  # first build libevent
    - autoreconf --install
    - ./configure --prefix=$PWD/../atlas
    - make install
    - cd ../
    - make menuconfig     # This creates a file called ".config"
    - make                # This creates the "busybox" executable
  artifacts:
    paths:
      - busybox
      - atlas/lib/*

test-ci-test:
  stage: test
  only:
    - ci-test
  image: $DOCKER_IMAGE
  script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/atlas/lib
    - cd testsuite
    - sh runtest
